/**
 * Illustrated icon assets generated by scripts/generate-assets.mjs
 * (OpenAI gpt-image-1, consistent cute sticker style, transparent PNGs).
 */
export const ICONS = {
  question: require("../../assets/icons/question.png"),
  dice: require("../../assets/icons/dice.png"),
  back: require("../../assets/icons/back.png"),
  speaker: require("../../assets/icons/speaker.png"),
  stop: require("../../assets/icons/stop.png"),
  mute: require("../../assets/icons/mute.png"),
  note: require("../../assets/icons/note.png"),
  history: require("../../assets/icons/history.png"),
  gear: require("../../assets/icons/gear.png"),
  ball: require("../../assets/icons/ball.png"),
  logo: require("../../assets/icons/logo.png"),
} as const;

export type IconName = keyof typeof ICONS;
